### ISSUE TITLE
JetBrains 

### ISSUE THREAD

**Issue by patricklinpl** [nwhacks/nwhacks2018_static#73] opened 2017-12-04 06:08 UTC
Please add this logo to the website.

## URL the Logo Should Point To
https://www.jetbrains.com/

## Tier (Select one of Micro, Kilo, Mega, Giga)
In-Kind

Thanks!

**Comment by d4l3k** [comment] 2017-12-04 06:10
duplicate of #64

**Closed as completed by d4l3k** 2017-12-04 06:10 UTC
